name: Merge Fork on Schedule

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  merge:
    name: Merge fork
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge main branch from fork
        run: |
          git fetch origin
          git checkout main
          git merge origin/main
          git push origin main
